# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b866e893796b521059583dcbd1bd2f540109e6dba81ed56b37b657bb2b01864e21673ef1c0dc2078eaa95d98a52f5abda4077c1b07219af9e0671acec35a1ee5
  youtube_api_key: AIzaSyAPjYkDq0-iiCd6W5-qCw46J-r0EW39L1U

test:
  secret_key_base: bf216532fd1a372879a5116cc594e9c37fa2fbc24569aae7a0bce85eb542a39608e9de7ed1a9bbbd2df1f79d8b047756f413bb9c6b96fbbb11807f32b65c3ec0
  youtube_api_key: AIzaSyAPjYkDq0-iiCd6W5-qCw46J-r0EW39L1U

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  you_api_key: <%= ENV["YOUTUBE_API_KEY"] %>
